package part2

import "testing"

// Note: A general scaffold for tests can be autogenerated by VSCode using right click -> "Go: Generate Unit Tests For Function".
// I am just using my own test structure here.

// Arrange
var input = []int{
	1721,
	979,
	366,
	299,
	675,
	1456,
}

func TestGetAnswer(t *testing.T) {
	// Act
	got := GetAnswer(input)

	// Assert
	if want := 241861950; got != want {
		t.Errorf("GetAnswer(%v) = %d; want %d", input, got, want)
	}
}
