package day7

// InvertedBagList ...
type InvertedBagList map[string]FitsXTimesIn

// FitsXTimesIn ...
type FitsXTimesIn map[string]int

// BagList ...
type BagList map[string]Contains

// Contains ...
type Contains map[string]int
